name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: Branch name
        required: true
        default: main
        type: string
      ENVIRONMENT:
        description: Deployment Environment (dev/stage/prod)
        required: true
        default: dev
        type: string
      AWS_REGION:
        description: AWS region to deploy infra
        required: true
        default: us-east-1
        type: string
      EKS_CLUSTER:
        description: EKS cluster name
        required: true
        type: string
      NAMESPACE:
        description: Namespace
        required: true
        type: string
      HELM_REPOSITORY:
        description: S3 helm repository name
        required: true
        type: string
      ECR_REPO:
        description: ECR repo name
        required: true
        type: string
      BUILD_ENV:
        description: Build env
        required: true
        type: string

