name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: "Branch name"
        required: true
        default: "main"
        type: choice
        options:
          - "main"
          - "temporal-sdk"
          - "development"
      ENVIRONMENT:
        description: "Deployment Environment (dev/stage/prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - prod
      AWS_REGION:
        description: "AWS region to deploy infra"
        required: true
        default: "us-east-1"
        type: choice
        options:
          - "me-central-1"
          - "us-east-1"
      EKS_CLUSTER:
        description: "EKS cluster name"
        required: true
        type: choice
        options:
          - "zamp-prd-uae-cluster"
          - "zamp-dev-us-cluster"
      NAMESPACE:
        description: "Namespace"
        required: true
        type: choice
        options:
          - "hcp"
          - "test"
      HELM_REPOSITORY:
        description: "S3 helm repository name"
        required: true
        type: choice
        options:
          - "zamp-prd-uae-helmcharts"
          - "zamp-dev-us-helmcharts"
      ECR_REPO:
        description: "ECR repo name"
        required: true
        type: choice
        options:
          - "zamp-prd-uae-pantheon-ecr"
          - "zamp-dev-us-pantheon-ecr"
      BUILD_ENV:
        description: "Build env"
        required: true
        type: choice
        options:
          - "awsprd"
          - "dev"
env:
  APP_NAME: hcp
  
jobs:
  prepare-env:
    name: Prepare Env
    runs-on: ubuntu-latest-m
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 2
    env:
      BRANCH: ${{ github.event.inputs.BRANCH }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
      AWS_REGION: ${{ github.event.inputs.AWS_REGION }}
      EKS_CLUSTER: ${{ github.event.inputs.EKS_CLUSTER }}
      NAMESPACE: ${{ github.event.inputs.NAMESPACE }}
      HELM_REPOSITORY: ${{ github.event.inputs.HELM_REPOSITORY }}
      ECR_REPO: ${{ github.event.inputs.ECR_REPO }}
      BUILD_ENV: ${{ github.event.inputs.BUILD_ENV }}
    outputs:
      APP_NAME: ${{ steps.vars.outputs.APP_NAME }}
      SLACK_WEBHOOK_URL: ${{ steps.vars.outputs.SLACK_WEBHOOK_URL }}
      STG_TRIGGER_TOKEN: ${{ github.event.client_payload.trigger_token }}
      PRD_TRIGGER_TOKEN: ${{ steps.vars.outputs.TRIGGER_TOKEN }}
      SSH_PRIVATE_KEY: ${{ steps.vars.outputs.SSH_PRIVATE_KEY }}
      HELM_CHART_NAME: ${{ steps.vars.outputs.HELM_CHART_NAME }}
      LABEL_SELECTOR: ${{ steps.vars.outputs.LABEL_SELECTOR }}
      APP_NAMES: ${{ steps.vars.outputs.APP_NAMES }}
      NEW_TAG: ${{ steps.tag.outputs.NEW_TAG }}
      AWS_ACCOUNT_ID: ${{ steps.set-account.outputs.AWS_ACCOUNT_ID }}
      ECR_REGISTRY: ${{ steps.registry.outputs.ECR_REGISTRY }}
      
