name: Deploy cluster components

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: "Branch name"
        required: true
        default: "main"
        type: choice
        options:
          - "main"
          - "uae"
          - "cluster-components-pipeline-v1"
      ENVIRONMENT:
        description: "Deployment Environment (dev/stage/prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - prod
      AWS_REGION:
        description: "AWS region to deploy infra"
        required: true
        default: "me-central-1"
        type: choice
        options:
          - "me-central-1"
          - "us-east-2"
      EKS_CLUSTER:
        description: "EKS cluster name"
        required: true
        type: choice
        options:
          - "zamp-prd-uae-cluster"
          - "CI-CD"
      NAMESPACE:
        description: "Namespace"
        required: true
        type: choice
        options:
          - "kube-system"
          - "traefik"
          - "cert-manager"
          - "windmill"
          - "monitoring"
          - "logging"
      HELM_RELEASE:
        description: "Chart to be deployed"
        required: true
        type: choice
        options:
          - "cert-manager"
          - "external-secrets"
          - "traefik"
          - "windmill"
          - "metrics-server"
          - "prometheus"
          - "grafana"
          - "elasticsearch"
          - "filebeat"
          - "kibana"
          - "karpenter"
      TEMPLATES_PATH:
        description: "Helm chart templates path"
        required: true
        type: choice
        options:
          - "cert-manager/charts/cert-manager"
          - "external-secrets"
          - "windmill"
          - "traefik/charts/traefik"
          - "metrics-server"
          - "prometheus"
          - "grafana"
          - "elasticsearch"
          - "filebeat"
          - "kibana"
          - "karpenter"
      VALUES_FILE:
        description: "Values File path"
        required: true
        type: choice
        options:
          - "values.yaml"
          - "charts/cert-manager/values.yaml --set installCRDs=true"
          - "charts/traefik/values.yaml"

concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  prepare-env:
    name: Prepare Env
    runs-on: ubuntu-latest
    timeout-minutes: 2

    env:
      BRANCH: ${{ github.event.inputs.BRANCH }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
      AWS_REGION: ${{ github.event.inputs.AWS_REGION }}
      EKS_CLUSTER: ${{ github.event.inputs.EKS_CLUSTER }}
      NAMESPACE: ${{ github.event.inputs.NAMESPACE }}
      HELM_RELEASE: ${{ github.event.inputs.HELM_RELEASE }}
      TEMPLATES_PATH: ${{ github.event.inputs.TEMPLATES_PATH }}
      VALUES_FILE: ${{ github.event.inputs.VALUES_FILE }}

    outputs:
      AWS_ACCOUNT_ID: ${{ steps.set-account.outputs.AWS_ACCOUNT_ID }}

    steps:
      - name: Determine AWS AccountID based on environment
        id: set-account
        run: |
          if [[ "$ENVIRONMENT" == "prod" ]]; then
            echo "AWS_ACCOUNT_ID=842675998483" >> $GITHUB_ENV  # Replace with actual Prod AWS Account ID
            echo "::set-output name=AWS_ACCOUNT_ID::842675998483"
          elif [[ "$ENVIRONMENT" == "stage" ]]; then
            echo "AWS_ACCOUNT_ID=123456789" >> $GITHUB_ENV  # Replace with actual Stage AWS Account ID
            echo "::set-output name=AWS_ACCOUNT_ID::123456789"
          else
            echo "AWS_ACCOUNT_ID=0123456789" >> $GITHUB_ENV  # Replace with actual Dev AWS Account ID
            echo "::set-output name=AWS_ACCOUNT_ID::0123456789"
          fi

      - name: Print selected values
        run: |
          echo "Branch: $BRANCH"
          echo "Environment: $ENVIRONMENT"
          echo "AWS Region: $AWS_REGION"
          echo "AWS Account ID: $AWS_ACCOUNT_ID"
          echo "EKS cluster: $EKS_CLUSTER"
          echo "Namespace: $NAMESPACE"
          echo "Helm release: $HELM_RELEASE"
          echo "Templates path: $TEMPLATES_PATH"
          echo "Values file: $VALUES_FILE"

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 15
    needs:
      - prepare-env
    env:
      BRANCH: ${{ github.event.inputs.BRANCH }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
      AWS_REGION: ${{ github.event.inputs.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ needs.prepare-env.outputs.AWS_ACCOUNT_ID }}
      EKS_CLUSTER: ${{ github.event.inputs.EKS_CLUSTER }}
      NAMESPACE: ${{ github.event.inputs.NAMESPACE }}
      HELM_RELEASE: ${{ github.event.inputs.HELM_RELEASE }}
      TEMPLATES_PATH: ${{ github.event.inputs.TEMPLATES_PATH }}
      VALUES_FILE: ${{ github.event.inputs.VALUES_FILE }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.BRANCH }}

      - name: "Set up AWS credentials using OIDC"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDCRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActionsSession

      - name: "Set up kubectl"
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER

      - name: "Install Helm"
        uses: azure/setup-helm@v4
        with:
          version: "v3.9.0"

      - name: "Set Grafana password based on environment"
        run: |
          if [[ "$ENVIRONMENT" == "prod" ]]; then
            echo "Setting Grafana password for prod"
            export GRAFANA_PASSWORD=${{ secrets.GRAFANA_PASSWORD_PROD }}
            export GRAFANA_SECRET_NAME="grafana-prod-secret"
          elif [[ "$ENVIRONMENT" == "stage" ]]; then
            echo "Setting Grafana password for stage"
            export GRAFANA_PASSWORD=${{ secrets.GRAFANA_PASSWORD_STAGE }}
            export GRAFANA_SECRET_NAME="grafana-stage-secret"
          else
            echo "Setting Grafana password for dev"
            export GRAFANA_PASSWORD=${{ secrets.GRAFANA_PASSWORD_DEV }}
            export GRAFANA_SECRET_NAME="grafana-dev-secret"
          fi

      - name: "Update values.yaml with Grafana secret name and password"
        run: |
          # Update the existingSecret field with the correct secret name
          sed -i "s/^existingSecret:.*/existingSecret: \"$GRAFANA_SECRET_NAME\"/" ./k8s-aws/"$TEMPLATES_PATH"/"$VALUES_FILE"
          # Update the passwordKey field with the correct password
          sed -i "s/^passwordKey:.*/passwordKey: \"$GRAFANA_PASSWORD\"/" ./k8s-aws/"$TEMPLATES_PATH"/"$VALUES_FILE"

      - name: "Install or Upgrade Helm chart"
        run: |
          helm upgrade --install "$HELM_RELEASE" ./k8s-aws/"$TEMPLATES_PATH" \
            --namespace "$NAMESPACE" \
            -f ./k8s-aws/"$HELM_RELEASE"/"$VALUES_FILE"
